[env:m5stack-cardputer]
platform = espressif32
board = m5stack-stamps3
framework = arduino
lib_deps =
    m5stack/M5Cardputer@^1.0.2
    bblanchon/ArduinoJson@^7.0.0
    links2004/WebSockets@^2.4.0
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_LOOP_STACK_SIZE=16384
extra_scripts = pre:load_config.py
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.filesystem = spiffs
board_build.embed_files = data/cert/x509_crt_bundle.bin
